name: Homework 4 CI

on:
  push:
    paths:
      - "Homework4/**.cxx"
      - "Homework4/data/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: centos:8
    steps:
      - run: |
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
          yum install -y git make gcc-c++

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache
        uses: actions/cache@v2
        with:
          path: Homework4/hw4_bnb
          key: $${{ hashFiles('Homework4/hw4_bnb.cxx') }}
      
      - run: |
          cd Homework4
          make test
